### ISSUE TITLE
Query(Not an issue): OpenSCToken on Mac OS 

### ISSUE THREAD

**Issue by cjn** [frankmorgner/OpenSCToken#12]
On installing the same I can see the PIV tokens listed in command line using "security list-smartcards".  The PIV token is read by both OpenSCToken and Apple built in PIV driver.

I am trying to write an application to access the certificates and key handle using the token ID which is possible using the KeyChain API SecItemCopyMatching. But it fails with error during signing operation with error errSecInvalidItemRef(-25304). 
Any suggestions as to how to access the certificates and identities using token ID?

**Comment by frankmorgner** [comment]
Sorry, I don't have special insights. Please refer to Apple's documentation and use their support if needed.
