### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by aphuang2013** [frankmorgner/OpenSCToken#16]
got 2 compile errors

1) getting an objectve-C error where I don't know how to fix it
Users/phuang/Desktop/workspace/OpenSCToken/OpenSCToken/Token.h:29:54: error: 
      pointer is missing a nullability type specifier (_Nonnull, _Nullable, or
      _Null_unspecified) [-Werror,-Wnullability-completeness]
static NSData* idToData(u8 type, struct sc_pkcs15_id *p15id)

2)   implicit conversion loses integer precision: 'CK_RV' (aka 'unsigned long')
      to 'int' [-Werror,-Wshorten-64-to-32]
        rc = sc_pkcs11_register_mechanism(p11card, mt);

I temporary it fix it by using casting

**Comment by frankmorgner** [comment]
I've fixed the first warning and tested with Safari and Login. #15 should work now.

**Comment by aphuang2013** [comment]
I have verified the compiling errors have gone.  let me close it
