### ISSUE TITLE
Outlook 2019 Issues

### ISSUE THREAD

**Issue by n3tl0kr** [frankmorgner/OpenSCToken#18]
Hey everyone,

I'm not entirely sure how to open an issue here but I'm seeing a problem with multiple prompting for auth when using Outlook 2019 on Mojave.  Can someone point me toward a quick way to unregister the security agent and remove this plugin for troubleshooting?

**Comment by frankmorgner** [comment]
For uninstalling, you can move OpenSCTokenApp to the trash bin or use `pluginkit -r` (see `man pluginkit`).

I cannot tell what's the problem with Outlook, your description is a little too unspecific...
