### ISSUE TITLE
OpenScToken to support network based token

### ISSUE THREAD

**Issue by RiteshAdobe** [frankmorgner/OpenSCToken#19]
Hi team,

We have a requirement where-in we have HSM boxes which are globally apart from mac-signing machines. Our current client has modified tokend module to support signing by fetching tokens over the network . 
Can you help me with configuring OpenSCToken to support the same?
Any clues/code fragment and pointers is will be highly appreciated.

**Comment by frankmorgner** [comment]
Use the [virtual smart card reader](https://frankmorgner.github.io/vsmartcard/index.html) or look here https://github.com/frankmorgner/vsmartcard/issues/150 for pointers.
