### ISSUE TITLE
Please respect SC_PKCS15_PRKEY_USAGE_ENCRYPT in OpenSCToken

### ISSUE THREAD

**Issue by jmastr** [frankmorgner/OpenSCToken#21]
Currently the certificate from my smartcard report under `Public Key Info -> Key Usage: Verify, Wrap, Derive`, but I need it to be `Encrypt, Verify, Wrap, Derive`.

https://github.com/frankmorgner/OpenSCToken/blob/84e0052e15b63fe87841187a413cdc42c0da6bb1/OpenSCToken/Token.m#L148
`prkey_info->usage` is `0x07`, which is according to: https://github.com/OpenSC/OpenSC/blob/ee78b0b80514460936c585c3ff5fc477338ae371/src/libopensc/pkcs15.h#L325-L327

```
SC_PKCS15_PRKEY_USAGE_ENCRYPT | SC_PKCS15_PRKEY_USAGE_DECRYPT | SC_PKCS15_PRKEY_USAGE_SIGN
```

I don't know, if this is even the right place to look. A private key cannot be used for encryption. 

I briefly checked the docs and there is a variable called [kSecAttrCanEncrypt](https://developer.apple.com/documentation/security/ksecattrcanencrypt) used for `Key Usage`, but I was not able to apply it somewhere.

**Comment by frankmorgner** [comment]
- If I understand correct, then there isn't any functional problem, instead you think that the reported flags aren't correct, right? (I.e. why do you *need it to be `Encrypt, Verify, Wrap, Derive`*?)

OpenSCToken only translates the private key attributes to the system:
https://github.com/frankmorgner/OpenSCToken/blob/84e0052e15b63fe87841187a413cdc42c0da6bb1/OpenSCToken/Token.m#L167-L187
I'm not sure where the public key attributes are coming from. I presume they are taken from the certificate flags. Can you have a look at your certs?

**Comment by jmastr** [comment]
I pulled the certificates from the card with:
```
% pkcs11-tool -r --id 45 --type cert > 45.cert
% pkcs11-tool -r --id 46 --type cert > 46.cert
```
The `45.cert` contains:
```
            X509v3 Key Usage: 
                Digital Signature
            X509v3 Extended Key Usage: 
                Microsoft Smartcardlogin, TLS Web Client Authentication
```
and `46.cert` contains:
```
            X509v3 Key Usage: 
                Digital Signature
            X509v3 Extended Key Usage: 
                E-mail Protection
```
In this ticket I am interested in the `E-mail Protection` part.

**Comment by jmastr** [comment]
This is what Apple makes out of it:

<img width="682" alt="Screenshot 2019-12-17 at 12 38 09" src="https://user-images.githubusercontent.com/11860038/70992503-21286700-20ca-11ea-9778-7cf766e6a009.png">

**Comment by jmastr** [comment]
I will do some digging...

**Comment by jmastr** [comment]
It is a little bit embarrassing, but it was just a certificate from the card missing. There is two signing and one encryption certificate on my card and the latter was not added to the driver. I wrote a small patch and will close the ticket with it.

Before:
```
% pkcs15-tool -c
Using reader with a card: Identiv SCR3500 C Contact Reader
X.509 Certificate [Signatur Zertifikat 1]
	Object Flags   : [0x02], modifiable
	Authority      : no
	Path           : df074331
	ID             : 45
	Encoded serial : 02 0A 4E3AB76500030006735A

X.509 Certificate [Signatur Zertifikat 2]
	Object Flags   : [0x02], modifiable
	Authority      : no
	Path           : df074332
	ID             : 46
	Encoded serial : 02 13 760000388F473163E4B64C5DFE00000000388F 
```

After:
```
% pkcs15-tool -c
Using reader with a card: Identiv SCR3500 C Contact Reader
X.509 Certificate [Signatur Zertifikat 1]
	Object Flags   : [0x02], modifiable
	Authority      : no
	Path           : df074331
	ID             : 45
	Encoded serial : 02 0A 4E3AB76500030006735A

X.509 Certificate [Signatur Zertifikat 2]
	Object Flags   : [0x02], modifiable
	Authority      : no
	Path           : df074332
	ID             : 46
	Encoded serial : 02 13 760000388F473163E4B64C5DFE00000000388F

X.509 Certificate [Verschluesselungs Zertifikat 1]
	Object Flags   : [0x02], modifiable
	Authority      : no
	Path           : df084331
	ID             : 4b
	Encoded serial : 02 13 7600003890A318E2F80195C3F6000000003890
```

The "new" certificate has:
```
            X509v3 Key Usage: critical
                Key Encipherment, Data Encipherment
```
And therefore is able to en-/decrypt.

**Comment by jmastr** [comment]
For everybody reading this: It was not `SC_PKCS15_PRKEY_USAGE_ENCRYPT`, but a missing certificate!
