### ISSUE TITLE
Mac Os Catalina 10.15.4

### ISSUE THREAD

**Issue by avvRobertoAlma** [frankmorgner/OpenSCToken#28]
It seems that on Mac Os Catalina 10.15.4, the OpenSCToken cannot access anymore to smartcard readers.

On 10.15.3, i can use the smartcard, on 10.15.4, instead, the output of `security list-smartcards` is always *No smartcards found* and obviously i cannot use smartcard.

Does anyone know if apple has changed anything in new Mac os 10.15.4 ?

**Comment by frankmorgner** [comment]
I've not yet managed to "notarize" the app, which is required for any app since 10.15, see https://github.com/OpenSC/OpenSC/issues/1934

**Comment by avvRobertoAlma** [comment]
**Update**
On Mac OS 10.15.4, using a smartcard reader, the OPENSC has worked.
The smart card is recognized and listed on the output of `security list-smartcards`. So, I guess open sc token still works.

TLS authentication only worked with **chromium**, while chrome and safari returned SSL error.

I don't know if this information may be useful, but that's it.

**Comment by frankmorgner** [comment]
That's strange, because Chrome is based on Chromium...

**Comment by avvRobertoAlma** [comment]
Yes, but that's it. I will try to find logs and return them to you.

I'm planning to perform some other tests on other friends' computers and i will draft a table.

Another strange issue of the world of smartcards for me (but concerns linux and not directly opensctoken) is mentioned on this [https://github.com/electron/electron/issues/20575](url).

**Comment by frankmorgner** [comment]
I think you should contact the chromium team...
