### ISSUE TITLE
com.apple.CryptoTokenKit.pivtoken disablement conflict 

### ISSUE THREAD

**Issue by jla3378** [frankmorgner/OpenSCToken#29]
I'm trying to avoid the minor issue that smart card certificates will be shown twice when listed for the user to choose to authenticate onto a website by disabling apple's built in framework with com.apple.CryptoTokenKit.pivtoken via `sudo defaults write /Library/Preferences/com.apple.security.smartcard DisabledTokens -array com.apple.CryptoTokenKit.pivtoken.` However, after a reboot, neither safari nor chrome will recognize ANY certificates despite `security list-smartcards` showing both `com.apple.pivtoken` and `org.opensc-project.mac.opensctoken.OpenSCTokenApp.OpenSCToken`. `sc_auth` to authenticate logons still works. I've used both the package that came with OpenSC 0.20.0 and the one created by compiling the latest code from the master branch.

Not fully understanding OpenSCToken's relation with CryptoTokenKit.pivtoken, it seems that OpenSCToken requires CryptoTokenKit.pivtoken to be enabled.

**Comment by frankmorgner** [comment]
OpenSCToken doesn't depend on Apple's pivtoken. Howerver, both token drivers can handle the PIV card, so there may be some conflict while using the token. Anyway, this shouldn't lead to missing certificates in your browser. I have no idea what's going wrong there...
