### ISSUE TITLE
Relevance of _this_ repository compared to OpenSC

### ISSUE THREAD

**Issue by afoeder** [frankmorgner/OpenSCToken#39]
Hi,

looking around makes the impression that the functionality of this repository (i.e. CryptoKit support) is present anyways also in OpenSC itself, at least since version 20. Is this correct and this repository is therefore kind of obsolete?
There are still commits tho… Anyways I would love to have an indication on the README.md because other people might wonder as well?

Thank a lot!

**Comment by frankmorgner** [comment]
OpenSCToken builds on the OpenSC libraries. OpenSCToken and all other OpenSC libraries are distributed in the OpenSC installer for mac.

If you think this can be clearified in the README.md, please make a pull request
