### ISSUE TITLE
Enable logging on Big Sur

### ISSUE THREAD

**Issue by blschatz** [frankmorgner/OpenSCToken#41]
I've previously enabled logging by editing the opensc.conf file in [1], and pointing debug_file to a location under my user profile. 

I cant seem to see any logging occurring now though. Has anything changed recently? How do I enable logging?

Thanks.

[1] /Applications/OpenSCTokenApp.app/Contents/PlugIns/OpenSCToken.appex/Contents/Resources/opensc.conf

**Comment by frankmorgner** [comment]
See https://github.com/frankmorgner/OpenSCToken#configuring-opensctoken
