### ISSUE TITLE
sc_ctx_use_reader: -1400 (Internal error)

### ISSUE THREAD

**Issue by angelocastaldo** [frankmorgner/OpenSCToken#42]
Hi,
I builded OpenSCToken with Xcode Version 12.4 on macOS Catalina (10.15.7). I ran OpenSCTokenApp but it doesn't work. 
I'm using a CNS Card and SCM SDI011 smart card readers.
Below you can find  the contains of file opens-debug.txt:
P:1092; T:0x123145371058176 10:34:20.318 [cryptotokenkit] ctx.c:855:sc_context_create: ===================================
P:1092; T:0x123145371058176 10:34:20.318 [cryptotokenkit] ctx.c:856:sc_context_create: opensc version: 0.21.0
P:1092; T:0x123145371058176 10:34:20.319 [cryptotokenkit] reader-pcsc.c:892:pcsc_init: PC/SC options: connect_exclusive=0 disconnect_action=0 transaction_end_action=0 reconnect_action=0 enable_pinpad=1 enable_pace=1
P:1092; T:0x123145371058176 10:34:20.320 [cryptotokenkit] reader-pcsc.c:1374:pcsc_detect_readers: called
P:1092; T:0x123145371058176 10:34:20.320 [cryptotokenkit] reader-pcsc.c:1387:pcsc_detect_readers: Probing PC/SC readers
P:1092; T:0x123145371058176 10:34:20.320 [cryptotokenkit] reader-pcsc.c:1440:pcsc_detect_readers: Establish PC/SC context
P:1092; T:0x123145371058176 10:34:20.337 [cryptotokenkit] reader-pcsc.c:1323:pcsc_add_reader: Adding new PC/SC reader 'SDI011 USB Smart Card Reader(1)'
P:1092; T:0x123145371058176 10:34:20.337 [cryptotokenkit] reader-pcsc.c:360:refresh_attributes: SDI011 USB Smart Card Reader(1) check
P:1092; T:0x123145371058176 10:34:20.338 [cryptotokenkit] reader-pcsc.c:407:refresh_attributes: current  state: 0x00000012
P:1092; T:0x123145371058176 10:34:20.338 [cryptotokenkit] reader-pcsc.c:408:refresh_attributes: previous state: 0x00000000
P:1092; T:0x123145371058176 10:34:20.338 [cryptotokenkit] reader-pcsc.c:464:refresh_attributes: card absent
P:1092; T:0x123145371058176 10:34:20.339 [cryptotokenkit] reader-pcsc.c:1532:pcsc_detect_readers: SDI011 USB Smart Card Reader(1):SCardConnect(DIRECT): 0x00000000
P:1092; T:0x123145371058176 10:34:20.339 [cryptotokenkit] reader-pcsc.c:1141:detect_reader_features: called
P:1092; T:0x123145371058176 10:34:20.339 [cryptotokenkit] reader-pcsc.c:1143:detect_reader_features: Requesting reader features ... 
P:1092; T:0x123145371058176 10:34:20.437 [cryptotokenkit] reader-pcsc.c:1323:pcsc_add_reader: Adding new PC/SC reader 'SDI011 USB Smart Card Reader(2)'
P:1092; T:0x123145371058176 10:34:20.437 [cryptotokenkit] reader-pcsc.c:360:refresh_attributes: SDI011 USB Smart Card Reader(2) check
P:1092; T:0x123145371058176 10:34:20.438 [cryptotokenkit] reader-pcsc.c:407:refresh_attributes: current  state: 0x00000012
P:1092; T:0x123145371058176 10:34:20.438 [cryptotokenkit] reader-pcsc.c:408:refresh_attributes: previous state: 0x00000000
P:1092; T:0x123145371058176 10:34:20.438 [cryptotokenkit] reader-pcsc.c:464:refresh_attributes: card absent
P:1092; T:0x123145371058176 10:34:20.439 [cryptotokenkit] reader-pcsc.c:1532:pcsc_detect_readers: SDI011 USB Smart Card Reader(2):SCardConnect(DIRECT): 0x00000000
P:1092; T:0x123145371058176 10:34:20.439 [cryptotokenkit] reader-pcsc.c:1141:detect_reader_features: called
P:1092; T:0x123145371058176 10:34:20.439 [cryptotokenkit] reader-pcsc.c:1143:detect_reader_features: Requesting reader features ... 
P:1092; T:0x123145371058176 10:34:20.521 [cryptotokenkit] reader-pcsc.c:1556:pcsc_detect_readers: returning with: 0 (Success)
P:1092; T:0x123145371058176 10:34:20.521 [cryptotokenkit] ctx.c:896:sc_ctx_use_reader: called
P:1092; T:0x123145371058176 10:34:20.521 [cryptotokenkit] reader-pcsc.c:2507:pcsc_use_reader: called
P:1092; T:0x123145371058176 10:34:20.521 [cryptotokenkit] reader-pcsc.c:2561:pcsc_use_reader: returning with: -1400 (Internal error)
P:1092; T:0x123145371058176 10:34:20.521 [cryptotokenkit] /Users/angelocastaldo/Desktop/Development/OpenSCToken-master/OpenSCToken/Token.m:94:-[OpenSCToken initWithSmartCard:AID:OpenSCDriver:error:]: sc_ctx_use_reader: -1400 (Internal error)**
P:1092; T:0x123145371058176 10:34:20.521 [cryptotokenkit] ctx.c:931:sc_release_context: called
P:1092; T:0x123145371058176 10:34:20.521 [cryptotokenkit] reader-pcsc.c:973:pcsc_finish: called

Thx
Angelo

**Comment by frankmorgner** [comment]
your log says that your card is *absent*...

**Comment by angelocastaldo** [comment]
Hi,
but my card is inserted in the reader.

**Comment by angelocastaldo** [comment]
I tried again and in this case my card is inserted in the reader but obtain same error.
see log below:
P:434; T:0x123145532760064 16:23:55.661 [cryptotokenkit] ctx.c:856:sc_context_create: opensc version: 0.21.0
P:434; T:0x123145532760064 16:23:55.662 [cryptotokenkit] reader-pcsc.c:892:pcsc_init: PC/SC options: connect_exclusive=0 disconnect_action=0 transaction_end_action=0 reconnect_action=0 enable_pinpad=1 enable_pace=1
P:434; T:0x123145532760064 16:23:55.665 [cryptotokenkit] reader-pcsc.c:1374:pcsc_detect_readers: called
P:434; T:0x123145532760064 16:23:55.666 [cryptotokenkit] reader-pcsc.c:1387:pcsc_detect_readers: Probing PC/SC readers
P:434; T:0x123145532760064 16:23:55.666 [cryptotokenkit] reader-pcsc.c:1440:pcsc_detect_readers: Establish PC/SC context
P:434; T:0x123145532760064 16:23:56.253 [cryptotokenkit] reader-pcsc.c:1323:pcsc_add_reader: Adding new PC/SC reader 'SDI011 USB Smart Card Reader(1)'
P:434; T:0x123145532760064 16:23:56.253 [cryptotokenkit] reader-pcsc.c:360:refresh_attributes: SDI011 USB Smart Card Reader(1) check
P:434; T:0x123145532760064 16:23:56.255 [cryptotokenkit] reader-pcsc.c:407:refresh_attributes: current  state: 0x00000022
P:434; T:0x123145532760064 16:23:56.255 [cryptotokenkit] reader-pcsc.c:408:refresh_attributes: previous state: 0x00000000
P:434; T:0x123145532760064 16:23:56.255 [cryptotokenkit] reader-pcsc.c:464:refresh_attributes: card present, changed
P:434; T:0x123145532760064 16:23:56.256 [cryptotokenkit] reader-pcsc.c:1541:pcsc_detect_readers: SDI011 USB Smart Card Reader(1):SCardConnect(SHARED): 0x00000000
P:434; T:0x123145532760064 16:23:56.256 [cryptotokenkit] reader-pcsc.c:1141:detect_reader_features: called
P:434; T:0x123145532760064 16:23:56.256 [cryptotokenkit] reader-pcsc.c:1143:detect_reader_features: Requesting reader features ... 
P:434; T:0x123145532760064 16:23:56.263 [cryptotokenkit] reader-pcsc.c:1323:pcsc_add_reader: Adding new PC/SC reader 'SDI011 USB Smart Card Reader(2)'
P:434; T:0x123145532760064 16:23:56.263 [cryptotokenkit] reader-pcsc.c:360:refresh_attributes: SDI011 USB Smart Card Reader(2) check
P:434; T:0x123145532760064 16:23:56.264 [cryptotokenkit] reader-pcsc.c:407:refresh_attributes: current  state: 0x00000012
P:434; T:0x123145532760064 16:23:56.264 [cryptotokenkit] reader-pcsc.c:408:refresh_attributes: previous state: 0x00000000
P:434; T:0x123145532760064 16:23:56.264 [cryptotokenkit] reader-pcsc.c:464:refresh_attributes: card absent
P:434; T:0x123145532760064 16:23:56.264 [cryptotokenkit] reader-pcsc.c:1532:pcsc_detect_readers: SDI011 USB Smart Card Reader(2):SCardConnect(DIRECT): 0x00000000
P:434; T:0x123145532760064 16:23:56.264 [cryptotokenkit] reader-pcsc.c:1141:detect_reader_features: called
P:434; T:0x123145532760064 16:23:56.264 [cryptotokenkit] reader-pcsc.c:1143:detect_reader_features: Requesting reader features ... 
P:434; T:0x123145532760064 16:23:56.266 [cryptotokenkit] reader-pcsc.c:1556:pcsc_detect_readers: returning with: 0 (Success)
P:434; T:0x123145532760064 16:23:56.266 [cryptotokenkit] ctx.c:896:sc_ctx_use_reader: called
P:434; T:0x123145532760064 16:23:56.266 [cryptotokenkit] reader-pcsc.c:2507:pcsc_use_reader: called
P:434; T:0x123145532760064 16:23:56.266 [cryptotokenkit] reader-pcsc.c:2561:pcsc_use_reader: returning with: -1400 (Internal error)
P:434; T:0x123145532760064 16:23:56.266 [cryptotokenkit] /Users/angelocastaldo/Desktop/Development/OpenSCToken-master/OpenSCToken/Token.m:94:-[OpenSCToken initWithSmartCard:AID:OpenSCDriver:error:]: sc_ctx_use_reader: -1400 (Internal error)
P:434; T:0x123145532760064 16:23:56.266 [cryptotokenkit] ctx.c:931:sc_release_context: called
P:434; T:0x123145532760064 16:23:56.266 [cryptotokenkit] reader-pcsc.c:973:pcsc_finish: called
