### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by johanhenselmans** [frankmorgner/OpenSCToken#5]
Tried to follow the instructions, the step

==========

xcodebuild -target OpenSCTokenApp -configuration Release -project OpenSCToken/OpenSCTokenApp.xcodeproj install DSTROOT=${PWD}/target

==========

led to

==========

clang: error: no such file or directory: '/Users/johan/projecten/smartcard/opensc/OpenSC/OpenSCToken/../openssl_bin/Library/OpenSC/lib/libcrypto.a'

** INSTALL FAILED **

==========

Seems the first step

==========

./configure --disable-pcsc  --enable-cryptotokenkit \
   --disable-openssl --disable-readline --disable-zlib --prefix=/Library/OpenSC

==========

prevents the third step to compile..

**Comment by frankmorgner** [comment]
Sorry, I don't understand the problem. I've also recently updated the README regarding the build process, which may be what you're looking for.
