### ISSUE TITLE
Does a self-build OpenSCToken also need custom built OpenSC?

### ISSUE THREAD

**Issue by deg0nz** [frankmorgner/OpenSCToken#52]
Hi,

I was able to build the current master branch of OpenSCToken and install it. Since #40 was supposed to fix https://github.com/OpenSC/OpenSC/issues/2605.

Unfortunately, the issue still persists on my machine. The native PIN Prompt doesn't show up.

Do I have to Compile a recent version of OpenSC too? Are there related changes "over there" that need to be taken into consideration?

Thanks and best regards
Beh

P.S.: Some more info I was able to observe, maybe this helps:

There is one thing different though: 

`sudo sc_auth pair` shows another error message now:

`Cannot pair user (public key hash: <obfuscated>). The operation couldn’t be completed. (CryptoTokenKit error -8.)` This message indicates, that the key itself can't be used for pairing. So some stuff semms to got fixed :)

**Comment by frankmorgner** [comment]
For a release, we are linking OpenSCToken statically against libopensc, which was built with support for CTK. Since CTK is required and we are not distributing this library, you need to build it yourself.

**Comment by deg0nz** [comment]
Thx for the hint. I'm closing this now.
