### ISSUE TITLE
DESRCACC100001 and opensc.conf not available in the repository

### ISSUE THREAD

**Issue by LudovicRousseau** [frankmorgner/OpenSCToken#6]
The Xcode project references the files ``OpenSC/etc/opensc.conf`` and ``OpenSC/etc/DESRCACC100001`` but the ``OpenSC/`` directory is **not** present in the repository.

Maybe you forgot a ``git add``and ``git push``?

**Comment by frankmorgner** [comment]
It will be present if you follow the [build process](https://github.com/frankmorgner/OpenSCToken#building-opensctoken). The files are part of OpenSC, which will be checked out with `./bootstrap`.

**Comment by LudovicRousseau** [comment]
What? I should read the doc? 😄
