### ISSUE TITLE
Login with AD

### ISSUE THREAD

**Issue by amaccuish** [frankmorgner/OpenSCToken#8]
I'm having real trouble getting smart card login to work on Mojave. I've installed and registered your CTK extension. "sudo system_profiler SPSmartCardsDataType" properly returns the certificate, and I have copied the example /etc/SmartcardLogin.plist provided by Apple to where it should be. I've set allowSmartCard to 1 and temporarily set cert revocation checks to 0 in /Library/Preferences/com.apple.security.smartcard.plist. Still the login window doesn't acknowledge the card. Is there something I've missed? Cheers!

**Comment by frankmorgner** [comment]
- Did you check whether your card works in OpenSC as expected (e.g. with pkcs11-tool)?
- Can you generate a debug log of OpenSC when running the CTK extension (see https://github.com/frankmorgner/OpenSCToken#configuring-opensctoken)?
- My card/certificates worked out of the box (as described here https://ludovicrousseau.blogspot.com/2018/09/smart-card-integration-in-macos-sierra.html) and I never had to change anything with the certificate settings, so it might still be possible that your certificate is rejected at the lower layers of macOS. If so, you may want to try https://github.com/OpenSC/pam_p11 combined with OpenSC's PKCS#11 module, which isn't very strict about the certificate properties.

**Comment by amaccuish** [comment]
Ahh I think I found the problem. The CTK extension is only being loaded for my user, not for everyone. How can I add it systemwide? (and yes the card works as expected with OpenSC)

**Comment by frankmorgner** [comment]
See https://github.com/frankmorgner/OpenSCToken#running-opensctoken:
```
sudo -u _securityagent pluginkit -a /Applications/OpenSCTokenApp.app/Contents/PlugIns/OpenSCToken.appex
```

**Comment by amaccuish** [comment]
That didn't work, it didn't actually register it for all users. I logged in as another user, listed the modules, and OpenSC wasn't present. In the end I went back to the old tokend setup.

**Comment by frankmorgner** [comment]
Sorry, I currently can't give you more insights than what's available in Apple's documentation.
