### ISSUE TITLE
Can't  Login to macOS with smart card

### ISSUE THREAD

**Issue by xaqfan** [frankmorgner/OpenSCToken#9]
Hi, I have a critical issue, when I login into MacOS with OpenSC smart card appex, it is able to succeed if I just use "lock screen". But if I "Logout", I cannot use my smart card to login, it looks like system doens't recognize my smart card in the login screen, it shows only input "Password", not "PIN". So I want to ask are there any other settings I should do?

**Comment by xaqfan** [comment]
oh,sorry.I need to register is globally. I have find  it .
but there are issues.
1
"sudo -u _securityagent  "  -- it will report error with"Illegal instruction: 4"
"sudo -u _securityagent pluginkit -a" -- it    is right.

2,when i restart my pc , It looks like system doens't recognize my smart card in the login screen.
It looks that need  to run up two cmds in background.

**Comment by frankmorgner** [comment]
Please update to a newer version of macOS, that should fix your problem, see https://stackoverflow.com/a/14285922
